[features]
seeds = false
skip-lint = false
[programs.localnet]
onchain_voting = "2tmrwL9JD9xiJod5FxMA6jfrpheM6vYM1h1gLYmCa3TG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
